const COMPANY = {
  name: "Al Maas Al Malaki Bldg. Mat. Tr",
  short: "Al Maas Al Malaki",
  tagline: "Steel Stockist, Supplier, Importer & Exporter — UAE & GCC",
  address: "Plot No. 10680, Al Sajaa Industrial Area, Sharjah, UAE",
  phone: "+971 6 579 3764",
  phoneHref: "tel:+97165793764",
  mobile: "+971 55 742 8754",
  mobileHref: "tel:+971557428754",
  email: "almaas.almalaki@outlook.com",
  hours: "Mon – Sat, 8:00 AM – 6:00 PM",
  whatsapp: "https://wa.me/971551893786?text=Hi%2C%20I%27m%20interested%20in%20your%20steel%20products",
  mapsEmbed: "https://www.google.com/maps?q=AL+MAAS+AL+MALAKI+BLDG+MAT+TR,+Al+Sajaa+Industrial+Area,+Sharjah,+UAE&output=embed",
  mapsPlaceUrl: "https://maps.app.goo.gl/PEUcJesUhEDXchxXA",
};

const structuralApps = ["Construction", "Fabrication", "Infrastructure", "Oil & Gas"];

const CATEGORIES = [
  {
    slug: "structural-steel",
    name: "Structural Steel",
    short: "Beams, channels, angles, flats, rounds and shaft bars for construction and fabrication.",
    image: "cat-structural.jpg",
    intro: "Al Maas Al Malaki is a leading structural steel supplier in the UAE and GCC, stocking a comprehensive range of hot-rolled beams, channels, angles, flat bars, round bars and shaft bars manufactured to international standards (ASTM, EN, JIS, BS). Our structural steel is trusted by fabricators, EPC contractors, construction firms and industrial workshops across Sharjah, Dubai, Abu Dhabi and the wider GCC for its consistent quality, verified mill test certificates and immediate availability from stock.",
    products: [
      { slug: "steel-beams", name: "Steel Beams (IPE / UB / H-Beams)", image: "prod-steel-beams.jpg", teaser: "IPE, UB and H-section steel beams for structural frames and heavy load-bearing applications.", description: "Our steel beams include IPE, UB (Universal Beams) and H-sections manufactured from S275JR / S355JR / A36 grade steel — engineered for structural frames, warehouses, industrial sheds, mezzanine floors and bridge construction across the UAE and GCC. Every beam ships with full mill test certificates (MTC) and traceability, and we maintain deep stock at our Al Sajaa yard for same-day dispatch on standard sizes.", specs: [{ label: "Material Grade", value: "S275JR, S355JR, ASTM A36" }, { label: "Standard", value: "EN 10025, ASTM A6/A6M" }, { label: "Sizes Available", value: "IPE 80 – IPE 600, UB 127 – UB 914, H 100 – H 400" }, { label: "Length", value: "6m, 9m, 12m (custom cut on request)" }, { label: "Finish", value: "Hot-rolled black / primer painted" }, { label: "Certification", value: "EN 10204 3.1 MTC" }], applications: structuralApps },
      { slug: "steel-channels", name: "Steel Channels (UPN / C-Channels)", image: "prod-steel-channels.jpg", teaser: "UPN and C-section channels for framing, brackets and structural supports.", description: "Steel channels (UPN and C-sections) are used extensively in structural framing, purlins, vehicle chassis and support brackets. We stock hot-rolled channels in mild steel grades to EN 10025 and ASTM A36, cut to length and delivered across the UAE from our Sharjah stockyard.", specs: [{ label: "Material Grade", value: "S235JR, S275JR, ASTM A36" }, { label: "Standard", value: "EN 10025, ASTM A6" }, { label: "Sizes Available", value: "UPN 50 – UPN 300, C 75 – C 300" }, { label: "Length", value: "6m / 12m standard" }, { label: "Finish", value: "Hot-rolled black" }, { label: "Certification", value: "EN 10204 3.1 MTC" }], applications: ["Structural framing", "Purlins", "Vehicle chassis", "Support brackets"] },
      { slug: "steel-angles", name: "Steel Angles (Equal & Unequal)", teaser: "Equal and unequal L-angles for bracing, frames and general fabrication.", description: "Hot-rolled equal and unequal steel angles for bracing, tower structures, trusses and general fabrication. Available in a wide range of sizes and grades with certified quality, ready for pickup or delivery anywhere in the UAE and GCC.", specs: [{ label: "Material Grade", value: "S235JR, S275JR, ASTM A36" }, { label: "Type", value: "Equal angle & Unequal angle" }, { label: "Sizes Available", value: "20x20x3 mm to 200x200x20 mm" }, { label: "Length", value: "6m standard" }, { label: "Finish", value: "Hot-rolled black" }, { label: "Application", value: "Trusses, towers, bracing, frames" }], applications: ["Trusses", "Towers", "Bracing", "Frames"] },
      { slug: "flat-bars", name: "Flat Bars", image: "prod-flat-bars.jpg", teaser: "Mild steel flat bars in a wide range of widths and thicknesses.", description: "Hot-rolled mild steel flat bars used for fabrication, gates, grilles, brackets and general engineering work. Stocked in multiple widths and thicknesses ready for immediate dispatch.", specs: [{ label: "Material Grade", value: "S235JR, ASTM A36" }, { label: "Width", value: "20 mm – 200 mm" }, { label: "Thickness", value: "3 mm – 25 mm" }, { label: "Length", value: "6m standard" }, { label: "Finish", value: "Hot-rolled" }, { label: "Standard", value: "EN 10058" }], applications: ["Fabrication", "Gates & grilles", "Brackets", "General engineering"] },
      { slug: "round-bars", name: "Round Bars", image: "prod-round-bars.jpg", teaser: "Hot-rolled mild steel round bars for machining and shafting.", description: "Mild steel round bars supplied in bright and black finishes for machining, turning, shafting and structural applications. Sourced from reputable mills with full traceability.", specs: [{ label: "Material Grade", value: "EN8, EN9, S355J2, C45" }, { label: "Diameter", value: "6 mm – 200 mm" }, { label: "Length", value: "6m standard, cut-to-length available" }, { label: "Finish", value: "Black / bright drawn" }, { label: "Standard", value: "EN 10060, EN 10083" }, { label: "Application", value: "Shafts, machined parts, structural" }], applications: ["Machining", "Shafting", "Fasteners", "Structural"] },
      { slug: "square-bars", name: "Square Bars", image: "prod-square-bars.jpg", teaser: "Hot-rolled mild and carbon steel square bars for fabrication, machining and structural framing.", description: "Al Maas Al Malaki supplies hot-rolled steel square bars in mild steel and carbon steel grades, stocked at our Al Sajaa yard in Sharjah for immediate dispatch across the UAE and GCC. Square bars are solid, four-sided sections used wherever a straight, uniform cross-section is needed for load-bearing, framing or machining — trusted by fabricators, machine shops and contractors for their dimensional accuracy and consistent mechanical properties. Every bar is manufactured to recognised international standards and supplied with full mill test certificates for traceability on regulated projects.", specs: [{ label: "Material Grade", value: "S235JR, S275JR, ASTM A36, EN8" }, { label: "Standard", value: "EN 10059, ASTM A29/A29M" }, { label: "Size Range", value: "10 mm x 10 mm to 100 mm x 100 mm" }, { label: "Length", value: "6m standard (cut-to-length available)" }, { label: "Finish", value: "Hot-rolled black / bright drawn" }, { label: "Certification", value: "EN 10204 3.1 MTC" }], applications: ["Fabrication", "Machining", "Structural framing", "Gates & grilles"] },
      { slug: "shaft-bars", name: "Shaft Bars", teaser: "Precision shaft bars for pumps, motors and rotating equipment.", description: "High-quality shaft bars in medium and high carbon steel grades, ideal for pumps, motors, gearboxes and rotating machinery components. Available bright-drawn and turned-and-polished for tight tolerances.", specs: [{ label: "Material Grade", value: "EN8, EN19, EN24, C45" }, { label: "Diameter", value: "10 mm – 250 mm" }, { label: "Length", value: "3m / 6m" }, { label: "Finish", value: "Bright drawn / turned & polished" }, { label: "Tolerance", value: "h9 / h11" }, { label: "Application", value: "Pump shafts, motor shafts, machinery" }], applications: ["Pumps", "Motors", "Gearboxes", "Rotating equipment"] },
    ],
  },
  {
    slug: "mild-steel-products",
    name: "Mild Steel (MS) Products",
    short: "MS sheets, chequered plates, HR sheets, tubes, hollow sections, angles, flats and rounds.",
    image: "cat-ms.jpg",
    intro: "As one of the UAE's most trusted mild steel (MS) suppliers, Al Maas Al Malaki carries a full range of MS sheets, chequered plates, hot-rolled sheets, tubes, hollow sections, angles, flat bars and round bars. Our mild steel products serve construction, oil & gas, workshops, fabricators and manufacturers across Sharjah, Dubai, Abu Dhabi and the GCC, backed by verified mill test certificates and reliable stock availability.",
    products: [
      { slug: "ms-sheets", name: "MS Sheets", teaser: "Cold-rolled and hot-rolled mild steel sheets in standard sizes.", description: "Mild steel sheets suitable for fabrication, ductwork, tank shells and general engineering. Supplied in cold-rolled and hot-rolled finishes across popular sizes for pickup or delivery across the UAE.", specs: [{ label: "Material Grade", value: "SPCC / SS400 / ASTM A36" }, { label: "Thickness", value: "0.5 mm – 12 mm" }, { label: "Size", value: "1250 x 2500 mm / 1500 x 3000 mm" }, { label: "Finish", value: "Cold-rolled / Hot-rolled" }, { label: "Standard", value: "JIS G3101 / ASTM A36" }, { label: "Application", value: "Fabrication, ducting, general use" }], applications: ["Fabrication", "Ducting", "Tank shells", "General engineering"] },
      { slug: "ms-chequered-sheets", name: "MS Chequered Sheets", image: "prod-ms-chequered-sheets.jpg", teaser: "Anti-skid chequered plates for flooring, ramps and platforms.", description: "MS chequered sheets (tear-drop pattern) provide anti-skid safety for flooring, stair treads, ramps, walkways and vehicle platforms. Stocked in popular sizes and thicknesses.", specs: [{ label: "Material Grade", value: "ASTM A36 / SS400" }, { label: "Pattern", value: "Tear-drop chequered" }, { label: "Thickness", value: "3 mm – 12 mm" }, { label: "Size", value: "1250 x 2500 mm / 1500 x 3000 mm" }, { label: "Finish", value: "Hot-rolled black" }, { label: "Application", value: "Anti-skid flooring & platforms" }], applications: ["Flooring", "Ramps", "Stair treads", "Walkways"] },
      { slug: "ms-hot-rolled-sheets", name: "MS Hot Rolled Sheets", teaser: "HR mild steel sheets and plates in thicker gauges.", description: "Hot-rolled MS sheets and plates in heavier gauges, used for structural fabrication, heavy engineering, storage tanks and pressure parts. Cut-to-size available.", specs: [{ label: "Material Grade", value: "ASTM A36 / S275JR / SS400" }, { label: "Thickness", value: "3 mm – 100 mm" }, { label: "Size", value: "Up to 2000 x 6000 mm" }, { label: "Finish", value: "Hot-rolled (HR)" }, { label: "Standard", value: "ASTM A36 / EN 10025" }, { label: "Certification", value: "EN 10204 3.1 MTC" }], applications: ["Structural fabrication", "Storage tanks", "Heavy engineering"] },
      { slug: "ms-tubes", name: "MS Tubes", image: "prod-ms-tubes.jpg", teaser: "Round, square and rectangular mild steel tubes.", description: "Mild steel tubes in round, square and rectangular profiles for structural, furniture, gate and general fabrication use. ERW manufactured with tight dimensional control.", specs: [{ label: "Type", value: "Round / Square / Rectangular" }, { label: "Material Grade", value: "S235JR / ASTM A500" }, { label: "Wall Thickness", value: "1.2 mm – 6 mm" }, { label: "Length", value: "6m standard" }, { label: "Finish", value: "Black / Pre-galvanized" }, { label: "Standard", value: "EN 10219 / ASTM A500" }], applications: ["Fabrication", "Furniture", "Gates", "Structural"] },
      { slug: "ms-hollow-sections", name: "MS Hollow Sections", image: "prod-ms-hollow-sections.jpg", image2: "prod-ms-hollow-sections-2.jpg", image3: "prod-ms-hollow-sections-3.jpg", image4: "prod-ms-hollow-sections-4.jpg", teaser: "SHS and RHS hollow structural sections for framing.", description: "Square (SHS) and rectangular (RHS) hollow sections for structural framing, columns, canopies and load-bearing members. ERW-welded to EN 10219 / ASTM A500 standards.", specs: [{ label: "Type", value: "SHS / RHS" }, { label: "Material Grade", value: "S235JR / S355J2H / A500" }, { label: "Size", value: "20x20 mm to 300x300 mm (SHS)" }, { label: "Wall Thickness", value: "1.5 mm – 12 mm" }, { label: "Length", value: "6m / 12m" }, { label: "Standard", value: "EN 10219, ASTM A500" }], applications: ["Structural framing", "Columns", "Canopies", "Trailers"] },
      { slug: "ms-angles", name: "MS Angles", image: "prod-ms-angles.jpg", teaser: "Mild steel L-angles in equal and unequal profiles.", description: "Equal and unequal mild steel angles for general fabrication, tower structures, brackets and trusses. Immediate stock availability at our Sharjah yard.", specs: [{ label: "Type", value: "Equal / Unequal angle" }, { label: "Grade", value: "S235JR / ASTM A36" }, { label: "Sizes", value: "25x25x3 to 150x150x15 mm" }, { label: "Length", value: "6m standard" }, { label: "Finish", value: "Hot-rolled" }, { label: "Standard", value: "EN 10056" }], applications: ["Fabrication", "Towers", "Trusses", "Brackets"] },
      { slug: "ms-flat-bars", name: "MS Flat Bars", image: "prod-ms-flat-bars.jpg", teaser: "Rectangular mild steel flat bars for fabrication.", description: "MS flat bars for general engineering, gates, grilles, brackets and fabricated structures. Multiple widths and thicknesses ex-stock.", specs: [{ label: "Grade", value: "S235JR / ASTM A36" }, { label: "Width", value: "20 mm – 250 mm" }, { label: "Thickness", value: "3 mm – 25 mm" }, { label: "Length", value: "6m" }, { label: "Finish", value: "Hot-rolled" }, { label: "Standard", value: "EN 10058" }], applications: ["Fabrication", "Grilles", "Brackets", "Bases"] },
      { slug: "ms-round-bars", name: "MS Round Bars", image: "prod-ms-round-bars.jpg", teaser: "Solid round bars in mild steel for machining and structural work.", description: "Mild steel round bars for machining, shafting, anchor bolts and structural components. Supplied black or bright-drawn.", specs: [{ label: "Grade", value: "S235JR / EN8 / C45" }, { label: "Diameter", value: "6 mm – 200 mm" }, { label: "Length", value: "6m" }, { label: "Finish", value: "Black / Bright" }, { label: "Standard", value: "EN 10060" }, { label: "Application", value: "Machining, anchor bolts, shafts" }], applications: ["Machining", "Anchor bolts", "Shafting"] },
    ],
  },
  {
    slug: "steel-pipes-tubes",
    name: "Steel Pipes & Tubes",
    short: "Seamless and ERW steel pipes, MS pipes, MS tubes and hollow sections.",
    image: "cat-pipes-2.jpg",
    intro: "Al Maas Al Malaki supplies a complete range of steel pipes and tubes across the UAE and GCC — including seamless and ERW carbon steel pipes, MS pipes, MS tubes, and structural hollow sections. Trusted by contractors in construction, oil & gas, water and infrastructure projects for consistent supply, certified quality and competitive pricing.",
    products: [
      { slug: "steel-pipes", name: "Steel Pipes (Seamless & ERW)", image: "prod-steel-pipes.jpg", teaser: "Carbon steel seamless and ERW pipes for fluid conveyance and structural use.", description: "Seamless and Electric Resistance Welded (ERW) carbon steel pipes for water lines, oil & gas transmission, fire fighting and structural applications. Available in schedules 40, 80 and XS.", specs: [{ label: "Type", value: "Seamless / ERW" }, { label: "Material Grade", value: "ASTM A106 Gr B / API 5L Gr B" }, { label: "Size (NB)", value: "1/2\" – 24\"" }, { label: "Schedule", value: "SCH 40 / SCH 80 / XS" }, { label: "Length", value: "6m / 12m" }, { label: "Standard", value: "ASTM A53, A106, API 5L" }], applications: ["Water lines", "Oil & gas", "Fire fighting", "Structural"] },
      { slug: "steel-tubes", name: "Steel Tubes", image: "prod-steel-tubes-main.jpg", image2: "prod-steel-tubes.jpg", image3: "prod-steel-tubes-3.jpg", teaser: "Structural and mechanical steel tubes in round, square and rectangular sections.", description: "Steel tubes for structural, mechanical and general engineering applications. ERW manufactured to EN 10219 / ASTM A500 with clean welds and precise dimensions.", specs: [{ label: "Type", value: "Round / Square / Rectangular" }, { label: "Grade", value: "S235JR / S355J2H / A500 Gr B" }, { label: "OD Range", value: "1/2\" – 12\"" }, { label: "Wall Thickness", value: "1.5 mm – 10 mm" }, { label: "Length", value: "6m / 12m" }, { label: "Standard", value: "EN 10219 / ASTM A500" }], applications: ["Structural", "Mechanical", "Furniture", "Handrails"] },
      { slug: "ms-pipes", name: "MS Pipes", teaser: "Mild steel round pipes for plumbing, scaffolding and general use.", description: "Mild steel round pipes commonly used for scaffolding, plumbing, water supply and low-pressure fluid transport. Black and pre-galvanized options in stock.", specs: [{ label: "Grade", value: "IS 1239 / BS 1387" }, { label: "Size (NB)", value: "1/2\" – 6\"" }, { label: "Class", value: "Light / Medium / Heavy" }, { label: "Length", value: "6m" }, { label: "Finish", value: "Black / Pre-galvanized" }, { label: "Standard", value: "IS 1239 / EN 10255" }], applications: ["Scaffolding", "Plumbing", "Water supply", "General"] },
      { slug: "ms-tubes-p", name: "MS Tubes", image: "prod-ms-tubes.jpg", teaser: "Square, round and rectangular MS tubes ex-stock.", description: "MS tubes in a full range of profiles for fabrication, furniture and structural use. Consistent wall thickness, straight lengths and burr-free ends.", specs: [{ label: "Type", value: "Round / Square / Rectangular" }, { label: "Grade", value: "S235JR" }, { label: "Wall", value: "1.2 mm – 6 mm" }, { label: "Length", value: "6m" }, { label: "Finish", value: "Black / Pre-galvanized" }, { label: "Standard", value: "EN 10219" }], applications: ["Fabrication", "Furniture", "Frames", "Gates"] },
      { slug: "ms-hollow-sections-p", name: "MS Hollow Sections", image: "prod-ms-hollow-sections.jpg", image2: "prod-ms-hollow-sections-2.jpg", image3: "prod-ms-hollow-sections-3.jpg", image4: "prod-ms-hollow-sections-4.jpg", teaser: "Structural SHS and RHS for framing and columns.", description: "Square and rectangular mild steel hollow sections for structural framing, columns and load-bearing applications, manufactured to EN 10219 and ASTM A500.", specs: [{ label: "Type", value: "SHS / RHS" }, { label: "Grade", value: "S235JR / S355J2H / A500" }, { label: "Size", value: "20x20 to 300x300 mm" }, { label: "Wall", value: "1.5 mm – 12 mm" }, { label: "Length", value: "6m / 12m" }, { label: "Standard", value: "EN 10219 / ASTM A500" }], applications: ["Framing", "Columns", "Canopies", "Structural"] },
    ],
  },
  {
    slug: "steel-sheets-coils",
    name: "Steel Sheets & Coils",
    short: "HR sheets, GI sheets, chequered sheets and steel coils in bulk quantities.",
    image: "cat-sheets.jpg",
    intro: "Al Maas Al Malaki is a bulk supplier of steel sheets and coils across the UAE and GCC — including hot-rolled sheets, galvanised iron (GI) sheets, chequered plates and cold/hot-rolled steel coils. Our supply chain and stockholding cover the needs of roll formers, roofing contractors, HVAC manufacturers, workshops and OEMs.",
    products: [
      { slug: "hr-steel-sheets", name: "Hot Rolled Steel Sheets", image: "prod-hr-steel-sheets.jpg", teaser: "HR sheets in structural and commercial quality grades.", description: "Hot-rolled steel sheets in structural and commercial grades for fabrication, heavy engineering, cutting and forming. Cut-to-size available.", specs: [{ label: "Grade", value: "ASTM A36 / SS400 / S275JR" }, { label: "Thickness", value: "1.5 mm – 25 mm" }, { label: "Size", value: "1250 x 2500 / 1500 x 3000 / 2000 x 6000 mm" }, { label: "Finish", value: "Hot-rolled (HR)" }, { label: "Standard", value: "ASTM A36 / EN 10025" }, { label: "Certification", value: "EN 10204 3.1 MTC" }], applications: ["Fabrication", "Heavy engineering", "Cutting & forming"] },
      { slug: "gi-sheets", name: "GI Sheets", teaser: "Galvanised iron sheets — plain and corrugated — for roofing and cladding.", description: "Galvanised iron (GI) sheets with a hot-dip zinc coating for excellent corrosion resistance, ideal for roofing, cladding, ducting and outdoor fabrication in the harsh UAE climate.", specs: [{ label: "Base Metal", value: "Cold-rolled / Hot-rolled steel" }, { label: "Coating", value: "Hot-dip galvanised, Z120 – Z275 g/m²" }, { label: "Thickness", value: "0.35 mm – 3 mm" }, { label: "Size", value: "1220 x 2440 / 1250 x 2500 mm" }, { label: "Finish", value: "Plain / Corrugated" }, { label: "Standard", value: "ASTM A653 / EN 10346" }], applications: ["Roofing", "Cladding", "Ducting", "Outdoor fabrication"] },
      { slug: "chequered-steel-sheets", name: "Chequered Steel Sheets", teaser: "Tear-drop chequered plates for anti-skid flooring.", description: "Chequered steel sheets (tear-drop pattern) delivering non-slip performance for flooring, stair treads, ramps and vehicle platforms in industrial environments.", specs: [{ label: "Grade", value: "SS400 / ASTM A36" }, { label: "Pattern", value: "Tear-drop" }, { label: "Thickness", value: "3 mm – 12 mm" }, { label: "Size", value: "1250 x 2500 / 1500 x 3000 mm" }, { label: "Finish", value: "Hot-rolled black" }, { label: "Application", value: "Anti-skid flooring" }], applications: ["Flooring", "Ramps", "Stair treads", "Vehicle platforms"] },
      { slug: "steel-coils", name: "Steel Coils", teaser: "HR, CR and GI steel coils for roll forming and stamping.", description: "Hot-rolled, cold-rolled and galvanised steel coils supplied in master and slit widths for roll formers, tube mills, panel manufacturers and HVAC producers.", specs: [{ label: "Type", value: "HR / CR / GI coils" }, { label: "Thickness", value: "0.35 mm – 8 mm" }, { label: "Coil Width", value: "600 mm – 1500 mm (slit to order)" }, { label: "Coil Weight", value: "3 – 15 MT" }, { label: "Grade", value: "SPCC / SPHC / DX51D / SS400" }, { label: "Standard", value: "JIS G3302 / EN 10346" }], applications: ["Roll forming", "Tube mills", "HVAC panels", "Stamping"] },
      { slug: "steel-roofing-sheets", name: "Steel Roofing Sheets", image: "prod-steel-roofing-sheets.jpg", teaser: "Colour-coated corrugated and trapezoidal steel roofing sheets for warehouses, sheds and villas.", description: "Al Maas Al Malaki supplies colour-coated and galvanised steel roofing sheets in corrugated and trapezoidal profiles, roll-formed from hot-dip galvanised or Galvalume steel coil for long-term weather and corrosion resistance in the UAE climate. Our roofing sheets are widely used for warehouses, labour camps, industrial sheds, villas and boundary walls, and are supplied cut to the exact running length required, minimising on-site waste. Every batch is backed by a durable polyester or PVDF paint coating and full mill documentation on request.", specs: [{ label: "Base Metal", value: "Galvanised steel / Galvalume (Al-Zn coated)" }, { label: "Profile", value: "Corrugated / Trapezoidal (box profile)" }, { label: "Thickness (BMT)", value: "0.35 mm – 0.7 mm" }, { label: "Coating", value: "Z100 – Z275 g/m² zinc, polyester colour coat" }, { label: "Sheet Width", value: "760 mm – 1000 mm effective cover" }, { label: "Length", value: "Cut to order, up to 12m" }, { label: "Standard", value: "ASTM A653 / EN 10346" }], applications: ["Warehouse roofing", "Industrial sheds", "Villa roofing", "Boundary walls & cladding"] },
    ],
  },
  {
    slug: "stainless-steel-products",
    name: "Stainless Steel Products",
    short: "Stainless steel sheets, round bars and general SS products in 304 / 316 grades.",
    image: "cat-ss.jpg",
    intro: "Al Maas Al Malaki stocks a wide range of stainless steel products in 304, 304L, 316 and 316L grades — including SS sheets, round bars and general SS items — serving food-processing, marine, chemical, architectural and pharmaceutical clients across the UAE and GCC.",
    products: [
      { slug: "stainless-steel-sheets", name: "Stainless Steel Sheets", image: "prod-stainless-steel-sheets.jpg", teaser: "SS 304 / 316 sheets in 2B, BA, No.4 and mirror finishes.", description: "Stainless steel sheets in 304, 304L, 316 and 316L grades with multiple surface finishes for architectural cladding, kitchen equipment, food processing and marine applications.", specs: [{ label: "Grade", value: "SS 304, 304L, 316, 316L" }, { label: "Thickness", value: "0.5 mm – 6 mm" }, { label: "Size", value: "1219 x 2438 / 1500 x 3000 mm" }, { label: "Finish", value: "2B / BA / No.4 / Mirror (8K)" }, { label: "Standard", value: "ASTM A240" }, { label: "Certification", value: "EN 10204 3.1 MTC" }], applications: ["Architecture", "Kitchens", "Food processing", "Marine"] },
      { slug: "ss-round-bars", name: "Stainless Steel Round Bars", teaser: "SS round bars for shafting, fasteners and machining.", description: "Stainless steel round bars in bright-drawn and peeled finishes for shafts, fasteners, pump parts and precision machining. Full traceability with MTC.", specs: [{ label: "Grade", value: "SS 304 / 316 / 316L / 410 / 431" }, { label: "Diameter", value: "3 mm – 200 mm" }, { label: "Length", value: "3m / 6m" }, { label: "Finish", value: "Bright drawn / Peeled" }, { label: "Standard", value: "ASTM A276 / EN 10088" }, { label: "Application", value: "Shafts, fasteners, pump parts" }], applications: ["Shafting", "Fasteners", "Machining", "Pump parts"] },
      { slug: "stainless-steel-products-item", name: "General Stainless Steel Products", teaser: "SS pipes, tubes, angles, flats and fittings on request.", description: "In addition to our stock SS sheets and round bars, we source SS pipes, tubes, angles, flat bars and pipe fittings on request in 304 and 316 grades — with quick lead times across the UAE and GCC.", specs: [{ label: "Grade", value: "SS 304 / 316" }, { label: "Product Range", value: "Pipes, tubes, angles, flats, fittings" }, { label: "Standard", value: "ASTM A312 / A554 / A276" }, { label: "Finish", value: "Pickled / Polished / No.4" }, { label: "Lead Time", value: "Ex-stock / 1–2 weeks indent" }, { label: "Certification", value: "EN 10204 3.1 MTC" }], applications: ["Process industry", "Chemical", "Marine", "Architecture"] },
    ],
  },
  {
    slug: "aluminum-products",
    name: "Aluminum Products",
    short: "Aluminium sheets and chequered plates in marine and architectural grades.",
    image: "cat-aluminum.jpg",
    intro: "Al Maas Al Malaki supplies aluminium sheets and chequered plates in marine and architectural grades for the UAE and GCC market. Our aluminium products serve marine, transport, cladding, HVAC and lightweight fabrication needs — corrosion-resistant, easy to form and long-lasting.",
    products: [
      { slug: "aluminum-sheets", name: "Aluminum Sheets", teaser: "Plain aluminium sheets in 1050, 3003, 5052 and 6061 grades.", description: "Plain aluminium sheets for cladding, signage, transport bodies, HVAC and lightweight fabrication. Available in mill finish and PE-coated variants.", specs: [{ label: "Alloy", value: "1050 / 3003 / 5052 / 6061" }, { label: "Thickness", value: "0.5 mm – 6 mm" }, { label: "Size", value: "1000 x 2000 / 1250 x 2500 mm" }, { label: "Temper", value: "H14 / H24 / T6" }, { label: "Finish", value: "Mill finish / PE-coated" }, { label: "Standard", value: "EN 573 / ASTM B209" }], applications: ["Cladding", "Signage", "Transport", "HVAC"] },
      { slug: "aluminum-chequered-sheets", name: "Aluminum Chequered Sheets", image: "prod-aluminum-chequered-sheets.jpg", image2: "prod-aluminum-chequered-sheets-2.jpg", teaser: "5-bar aluminium chequered plates for flooring and treads.", description: "Aluminium chequered sheets with a 5-bar tread pattern — lightweight, corrosion-resistant and anti-skid — used for flooring, stair treads, vehicle floors and toolboxes.", specs: [{ label: "Alloy", value: "3003 / 5052" }, { label: "Pattern", value: "5-bar tread" }, { label: "Thickness", value: "1.5 mm – 6 mm" }, { label: "Size", value: "1250 x 2500 mm" }, { label: "Finish", value: "Mill finish" }, { label: "Application", value: "Flooring, treads, vehicle floors" }], applications: ["Flooring", "Stair treads", "Vehicles", "Toolboxes"] },
    ],
  },
  {
    slug: "mesh-gratings",
    name: "Mesh & Gratings",
    short: "Expanded metal mesh, MS mesh, steel mesh and channel gratings.",
    image: "cat-mesh.jpg",
    intro: "Al Maas Al Malaki supplies expanded metal mesh, welded steel mesh, MS expanded mesh and channel gratings across the UAE and GCC. Our mesh and gratings products are used for walkways, platforms, façades, safety screens, drainage covers and industrial flooring — engineered for load, slip resistance and long service life.",
    products: [
      { slug: "expanded-metal-mesh", name: "Expanded Metal Mesh", image: "prod-expanded-metal-mesh.jpg", image2: "prod-expanded-metal-mesh-2.jpg", teaser: "Diamond-pattern expanded mesh for security, façades and walkways.", description: "Expanded metal mesh cut and stretched from single sheets — no welds, high strength-to-weight ratio — used for façades, security screens, walkways and safety guards.", specs: [{ label: "Material", value: "Mild steel / SS 304 / Aluminium" }, { label: "Pattern", value: "Diamond / Hexagonal" }, { label: "Sheet Size", value: "1250 x 2500 mm" }, { label: "Strand Thickness", value: "1.5 mm – 6 mm" }, { label: "Finish", value: "Mill / Galvanised / Painted" }, { label: "Application", value: "Façades, walkways, security" }], applications: ["Façades", "Walkways", "Security screens", "Guards"] },
      { slug: "ms-expanded-metal-mesh", name: "MS Expanded Metal Mesh", image: "prod-ms-expanded-metal-mesh.jpg", teaser: "Mild steel expanded mesh in standard and heavy-duty variants.", description: "Mild steel expanded metal mesh in standard and heavy-duty variants — ideal for platforms, ramps, safety screens and general industrial fabrication.", specs: [{ label: "Material", value: "Mild steel (S235JR)" }, { label: "Pattern", value: "Diamond expanded" }, { label: "Sheet Size", value: "1220 x 2440 / 1250 x 2500 mm" }, { label: "Thickness", value: "2 mm – 6 mm" }, { label: "Finish", value: "Black / Galvanised" }, { label: "Standard", value: "ASTM F1267" }], applications: ["Platforms", "Ramps", "Safety screens", "Fabrication"] },
      { slug: "steel-mesh", name: "Steel Mesh (Welded)", teaser: "Welded steel wire mesh in panels and rolls.", description: "Welded steel wire mesh for reinforcement, fencing, cages, partitions and general construction — supplied in panels and rolls with consistent square openings.", specs: [{ label: "Type", value: "Welded wire mesh — panels & rolls" }, { label: "Wire Diameter", value: "2 mm – 8 mm" }, { label: "Opening", value: "25 x 25 mm to 150 x 150 mm" }, { label: "Panel Size", value: "1200 x 2400 / 2000 x 3000 mm" }, { label: "Finish", value: "Black / Galvanised / PVC-coated" }, { label: "Application", value: "Reinforcement, fencing, cages" }], applications: ["Reinforcement", "Fencing", "Cages", "Partitions"] },
      { slug: "channel-gratings", name: "Channel Gratings", image: "prod-channel-gratings.jpg", image2: "prod-channel-gratings-2.jpg", image3: "prod-channel-gratings-3.jpg", teaser: "Steel channel gratings for drainage and industrial flooring.", description: "Steel channel gratings for drainage covers, trench covers and industrial flooring — engineered load ratings, slip-resistant surface and hot-dip galvanised for corrosion protection.", specs: [{ label: "Type", value: "Welded / Press-locked grating" }, { label: "Material", value: "Mild steel" }, { label: "Bearing Bar", value: "25x3 to 65x5 mm" }, { label: "Pitch", value: "30 mm x 100 mm typical" }, { label: "Finish", value: "Hot-dip galvanised" }, { label: "Load Class", value: "A15 – E600 (as required)" }], applications: ["Drainage covers", "Trench covers", "Industrial flooring", "Walkways"] },
    ],
  },
];

CATEGORIES.forEach((c) => { c.navProducts = c.products.slice(0, 3); });

const INDUSTRIES = [
  { title: "Construction & Real Estate", desc: "Structural steel, beams, rebar and hollow sections for high-rises, villas and commercial developments across the UAE.", image: "industry-construction.jpg" },
  { title: "Oil, Gas & Petrochemicals", desc: "Seamless & ERW pipes, flanges and heavy plates for refineries, pipelines and downstream facilities across the GCC.", image: "industry-oilgas.jpg" },
  { title: "Steel Fabrication & Workshops", desc: "MS plates, angles, channels and sheets supplied ex-stock to fabricators, welding shops and structural workshops.", image: "industry-fabrication.jpg" },
  { title: "Infrastructure & Bridges", desc: "Heavy structural sections, plates and reinforcement steel for bridges, highways, tunnels and public infrastructure.", image: "industry-infrastructure.jpg" },
  { title: "Manufacturing & OEM", desc: "Stainless steel, aluminium sheets and precision bars for OEMs, machinery builders and industrial equipment makers.", image: "industry-manufacturing.jpg" },
  { title: "Marine & Shipbuilding", desc: "Marine-grade steel plates, pipes and stainless sections for shipyards, port infrastructure and offshore projects.", image: "industry-marine.jpg" },
];

const FAQS = [
  { q: "Who is Al Maas Al Malaki and what steel products do you supply in the UAE?", a: "Al Maas Al Malaki Building Materials Trading is a Sharjah-based steel stockist, supplier, importer and exporter serving the UAE and the wider GCC. We stock a full range of structural steel, mild steel (MS) products, steel pipes & tubes, sheets & coils, stainless steel, aluminium products and mesh & gratings — ready for pickup or delivery." },
  { q: "Which regions do you deliver steel to across the GCC?", a: "From our Al Sajaa Industrial Area yard in Sharjah, we deliver across the UAE — Dubai, Abu Dhabi, Ajman, Ras Al Khaimah, Fujairah and Umm Al Quwain — and export throughout the GCC to Saudi Arabia, Oman, Qatar, Kuwait and Bahrain." },
  { q: "Do you provide mill test certificates (MTC) with your steel products?", a: "Yes. Every consignment of structural steel, MS products, stainless steel, pipes and plates is supplied with EN 10204 3.1 mill test certificates for full material traceability and quality assurance on your project." },
  { q: "What is the minimum order quantity for steel from your Sharjah stockyard?", a: "We serve everything from single-length trade orders to bulk project supply and container-load exports. There is no strict minimum — contact our sales team for a fast quotation on any size requirement." },
  { q: "Can you cut steel to size or arrange custom lengths?", a: "Yes. We offer cut-to-length services on beams, channels, angles, pipes, sheets and plates so contractors and fabricators receive material ready for use, reducing waste and on-site handling." },
  { q: "How quickly can you deliver steel in the UAE?", a: "Standard sizes ship same-day or next-day from our Sharjah stockyard across the UAE. Project quantities and export shipments to the GCC are typically dispatched within 2–5 working days depending on volume and destination." },
];

function getCategory(slug) { return CATEGORIES.find((c) => c.slug === slug); }
function getProduct(catSlug, prodSlug) {
  const cat = getCategory(catSlug);
  if (!cat) return undefined;
  const product = cat.products.find((p) => p.slug === prodSlug);
  return product ? { category: cat, product } : undefined;
}

window.CATALOG = { COMPANY, CATEGORIES, INDUSTRIES, FAQS, getCategory, getProduct };
